server:
  port: 8081
  servlet:
    context-path: /


logging:
  level:
    org.springframework.web.+:
      TRACE



default:
  found: Book not found
  format: Invalid data format. Adjust the values.
  link: -http://localhost:8081



spring:
  datasource:
    url: jdbc:postgresql://localhost:9000/postgres
    username: postgres
    password: hello
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true

  security:
    user:
      name: admin
      password: admin

